name: CI

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -V
      - name: Build
        run: echo "Build ok"

  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install Flask
      - run: python3 app.py
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Expose Docker container
        run: docker run -d -p 8000:8000 eronbetine/pucpr:latest

      - name: Install agent
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | \
            sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
            echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | \
            sudo tee /etc/apt/sources.list.d/ngrok.list && \
            sudo apt update && sudo apt install ngrok

      - name: Connect agente for token
        run: ngrok config add-authtoken 2Of8cjvsY1tEObyUzi5kDaA1V0Q_syZg7DQ5VkhfeT7Kceqs

      - name: Wait for Ngrok to start
        run: Start-Sleep -Seconds 10

      - name: Init Ngrok
        run: ngrok http 8000

      - name: Deploy
        run: echo "Deploy ok"



