name: CI/CD Pipeline
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install pip
        run: |
          python -m ensurepip --default-pip
          pip install --upgrade pip
      - name: Install Flask
        run: pip install Flask
      - name: Install Bandit
        run: pip install bandit
      - name: Build
        run: echo "Build ok"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2.4.4
        with:
          languages: python
      - name: Security Code Scan
        uses: github/codeql-action/analyze@v2.4.4
        with:
          database: codeql-database
      - name: Upload SAST report
        if: always()
        uses: actions/upload-artifact@v2.2.6
        with:
          name: SAST report
          path: results.sarif
      - name: Test
        run: echo "Teste SAST ok"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploy ok"
