name: CI/CD Pipeline
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install pip
        run: |
          python -m ensurepip --default-pip
          pip install --upgrade pip
      - name: Install Flask
        run: pip install Flask
      - name: Install Bandit
        run: pip install bandit
      - name: Build
        run: echo "Build ok"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python
      - name: Security Code Scan
        uses: github/codeql-action/analyze@v2
        with:
          database: codeql-database
      - name: Upload SAST report
        uses: actions/upload-artifact@v2
        with:
          name: SAST report
          path: ./python.sarif
      - name: Test
        env:
          MY_SECRET: ${{ secrets.MY_TOKEN }}
        run: |
          echo "Teste SAST ok"
          echo "My secret is $MY_TOKEN"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: eronbetine/pucpr:latest

      - name: Deploy
        run: echo "Deploy ok"


        