name: CI

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -V
      - name: Build
        run: echo "Build ok"

  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 app.py
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"

  deploy-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: eronbetine/pucpr:latest

      - name: Expose Docker container with Ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          docker run -d -p 8000:8000 eronbetine/pucpr:latest
          curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip > ngrok.zip
          unzip ngrok.zip
          ./ngrok authtoken $NGROK_AUTH_TOKEN
          ./ngrok http 8000

      - name: Deploy
        run: echo "Deploy ok"