name: CI

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -V
      - name: Build
        run: echo "Build ok"

  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install Flask
      - run: python3 app.py
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Expose Docker container
        run: docker run -d -p 8000:8000 eronbetine/pucpr:latest

      - name: Extract Ngrok
        run: sudo snap install ngrok-v3-stable-linux-amd64.tgz

      - name: Authenticate Ngrok
        run: ngrok config add-authtoken $NGROK_AUTH_TOKEN

      - name: Wait for Ngrok to start
        run: Start-Sleep -Seconds 10

      - name: Expose app with Ngrok
        run: ./ngrok http 8000

      - name: Deploy
        run: echo "Deploy ok"

